### PR TITLE
 Adjustment

### PR DESCRIPTION
**Pull request by RonildoSouza**

### CODE REVIEW

**Comment by FichteFoll** [comment]
The PR is conflicting.

**Comment by RonildoSouza** [comment]
FichteFoll.
Should you delete the file package.json.
According to the guidelines of "wbond".

https://github.com/wbond/package_control_channel/pull/5742

I'm not able to correct the PR.

**Comment by FichteFoll** [comment]
I will do it, depending on the outcome of wbond/package_control_channel#5742.

**Comment by RonildoSouza** [comment]
Ok. thanks.

**Pull request closed without merging**
